_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.2
            "8":
                - 5
                - 9
            "12": 0.19.2
            "13": linux-x86_64
