name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install gsutil
      if: runner.os != 'Windows'  # gsutil is pre-installed on Ubuntu and macOS
      run: |
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-455.0.0-linux-x86_64.tar.gz
        tar -xf google-cloud-cli-455.0.0-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh --quiet
        echo "$HOME/google-cloud-sdk/bin" >> $GITHUB_PATH

    - name: Install gsutil (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install gsutil

    - name: Download data
      run: |
        gsutil cp -r gs://emils_mlops_data_bucket/data .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Test with pytest
      run: |
        pytest -v